# Generated by Django 2.0.6 on 2018-09-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quesion', models.TextField()),
                ('option_1', models.CharField(max_length=300)),
                ('option_2', models.CharField(max_length=300)),
                ('option_3', models.CharField(max_length=300)),
                ('option_4', models.CharField(max_length=300)),
                ('answer', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Registered_Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=100)),
                ('phone_no', models.CharField(default=None, max_length=10)),
            ],
        ),
    ]
