# Generated by Django 2.0.6 on 2018-09-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='quesion',
            new_name='question',
        ),
        migrations.AlterField(
            model_name='registered_users',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
