# Generated by Django 2.0.6 on 2018-09-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20180911_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='answer',
            field=models.IntegerField(max_length=5),
        ),
    ]
